$image = /home/pepushi/Pictures/Wallpapers/second wallpaper lol.jpg

$background = rgba(191206ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(382f20ff)

$inverse_primary = rgba(7d5800ff)

$inverse_surface = rgba(f1e0caff)

$on_background = rgba(f1e0caff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(422c00ff)

$on_primary_container = rgba(ffdea9ff)

$on_primary_fixed = rgba(271900ff)

$on_primary_fixed_variant = rgba(5e4100ff)

$on_secondary = rgba(3c2f04ff)

$on_secondary_container = rgba(f8e0a6ff)

$on_secondary_fixed = rgba(241a00ff)

$on_secondary_fixed_variant = rgba(544519ff)

$on_surface = rgba(f1e0caff)

$on_surface_variant = rgba(d4c4afff)

$on_tertiary = rgba(383000ff)

$on_tertiary_container = rgba(f3e393ff)

$on_tertiary_fixed = rgba(211c00ff)

$on_tertiary_fixed_variant = rgba(514704ff)

$outline = rgba(9c8f7bff)

$outline_variant = rgba(504535ff)

$primary = rgba(ffba28ff)

$primary_container = rgba(5e4100ff)

$primary_fixed = rgba(ffdea9ff)

$primary_fixed_dim = rgba(ffba28ff)

$scrim = rgba(000000ff)

$secondary = rgba(dbc48cff)

$secondary_container = rgba(544519ff)

$secondary_fixed = rgba(f8e0a6ff)

$secondary_fixed_dim = rgba(dbc48cff)

$shadow = rgba(000000ff)

$source_color = rgba(eac078ff)

$surface = rgba(191206ff)

$surface_bright = rgba(413828ff)

$surface_container = rgba(271e11ff)

$surface_container_high = rgba(31291aff)

$surface_container_highest = rgba(3d3324ff)

$surface_container_low = rgba(221a0dff)

$surface_container_lowest = rgba(140d03ff)

$surface_dim = rgba(191206ff)

$surface_tint = rgba(ffba28ff)

$surface_variant = rgba(504535ff)

$tertiary = rgba(d6c77aff)

$tertiary_container = rgba(514704ff)

$tertiary_fixed = rgba(f3e393ff)

$tertiary_fixed_dim = rgba(d6c77aff)

