--  hl.permission({ binary = "/usr/bin/grim", type = "screencopy", mode = "allow" })
--  hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
--  hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")